# Use este arquivo para definir configurações locais para seu projeto.
# Qualquer configuração definida aqui vai tomar precedência sobre as globais.
# As configurações globais podem ser encontradas em `C:\Users\niimi\AppData\Roaming\YGOFabrica\config.toml`.

[expansion.niimiyo-jjba]
default = true
recipe = [ 'setup.toml', 'jojo.toml' ]

[picset.regular]
locale = 'en'
default = true
year = 2021
author = "Nii Miyo"
size = "421x"
