[macro]
PT = "per turn"
OPT = "Once ${PT}"
SbP = "Standby Phase"
QE = "(Quick Effect)"
BP = "Battle Phase"
DS = "Damage Step"
SU = "Stand User$1"
SP = "Stand Power$1"
StandText = """You can only control 1 "${SP| $1}". Can only be equipped to a "${SU| $2}" you control. If the monster this card is equipped to would be destroyed by battle or card effect: You can destroy this card instead."""

[set.standuser]
name = "${SU}"
code = 0xf00

[set.standpower]
name = "${SP}"
code = 0xf01

[[card]]
id = 1090076073
name = "Jonathan Joestar"
# set = "your_setname"
type = "monster effect"
effect = """Unaffected by the effect of Zombie monsters. At the start of the ${DS}, if this card battles a Zombie monster while in face-up attack position: You can destroy that monster, and if you do, your opponent takes damage equals half that monster's original ATK."""
atk = 2000
def = 1800
level = 6
race = "warrior"
attribute = "light"
category = "destroy_monster negate_effect"

[[card]]
id = 1090076074
name = "${SU| Kujo Jotaro}"
set = "standuser"
type = "monster effect"
effect = "If this card destroys a monster by battle: It gains 200 ATK."
atk = 1500
def = 1000
level = 4
race = "warrior"
attribute = "earth"
category = "change_atk_def"

[[card]]
id = 1090076075
name = "${SP| Star Platinum}"
set = "standpower"
type = "spell equip"
effect = """${StandText|Star Platinum|Kujo Jotaro}
While this card is equipped to a monster:
• It gains 1000 ATK;
• It can attack twice per ${BP};
• It cannot be destroyed by battle."""
strings = ["Destroy this card instead", "Gains 1000 ATK", "Attack twice", "Cannot be destroyed by battle"]
category = "destroy_st change_atk_def multi_attack"

[[card]]
id = 1090076072
name = "${SU| Higashikata Josuke}"
set = "standuser"
type = "monster effect"
effect = """At the start of the ${DS}, if this card battles a Reptile monster: It loses 200 ATK until the end of the ${BP}."""
atk = 1400
def = 1000
level = 4
race = "warrior"
attribute = "earth"
category = "change_atk_def"

[[card]]
id = 1090076076
name = "${SP| Crazy Diamond}"
set = "standpower"
type = "spell equip"
# ot = "ocg tcg"
effect = """${StandText|Crazy Diamond|Higashikata Josuke}
While this card is equipped to a monster:
• It gains 900 ATK;
• It can attack twice per ${BP};
• ${OPT}: you can target 1 monster you control that this card is not equipped to: Gain LP equal to half its ATK."""
strings = ["Destroy this card instead", "Gains 900 ATK", "Attack twice", "Gain LP"]
category = "destroy_st change_atk_def recover_lp"

[[card]]
id = 1090076077
name = "Meteorite Arrow"
type = "spell"
effect = """Target 1 face-up "${SU}" monster you control; add from your deck to your hand 1 "${SP}" card that specifically lists the targeted monster. You can only activate 1 "Meteorite Arrow" ${PT}."""
category = "send_to_hand search"

[[card]]
id = 1090076078
name = "Do You Believe in Gravity?"
type = "spell continuous"
effect = """During your ${SbP}, if you control a "${SU}" face-up monster: add (from your deck) to your hand 1 "${SU}" monster or 1 "Meteorite Arrow". You can only use this effect of "Do You Believe in Gravity?" once ${PT}."""
category = "send_to_hand search"

[[card]]
id = 1090076079
name = "${SU| Giorno Giovanna}"
set = "standuser"
type = "monster effect"
effect = """Target 1 "Meteorite Arrow" in your GY; add it to your hand. You can only use this effect of "${SU| Giorno Giovanna}" once ${PT}."""
atk = 1400
def = 1700
level = 4
race = "warrior"
attribute = "earth"
strings = ["Negate attack"]

[[card]]
id = 1090076080
name = "${SP| Gold Experience}"
set = "standpower"
type = "spell equip"
# ot = "ocg tcg"
effect = """${StandText|Gold Experience|Giorno Giovanna}
While this card is equipped to a monster:
• It gains 500 ATK and 800 DEF;
• It can attack twice per ${BP};
• It inflicts piercing battle damage
• ${OPT}: you can target 1 monster in your GY: Special Summon it, but banish it when it leaves the field."""
strings = ["Destroy this card instead", "Gains 500 ATK/DEF", "Attack twice", "Piercing damage", "Special Summon from GY"]
category = "destroy_st banish change_atk_def piercing multi_attack special_summon"

[[card]]
id = 1090076081
name = "${SP| Gold Experience Requiem}"
set = "standpower"
type = "monster effect fusion nomi"
# flavor-text = This card is cool
effect = """You can only control 1 "${SP| Gold Experience Requiem}". Must first be Special Summoned from your extra deck by tributing 1 "${SU| Giorno Giovanna}" you control who has a "${SP| Gold Experience}" equipped to it and banishing face-up 1 "Meteorite Arrow" from your hand.
Unaffected by other cards' effects. Cannot be targeted by your opponent's card effects. This card on the field cannot be destroyed by battle or card effect. Cannot be used as cost.
At the start of the ${DS}, if this card battles a monster: Negate the attack, and if you do, banish that monster.
If this card attacks your opponent directly: You win the duel.
All effects of this card cannot be negated."""
atk = "?"
def = "?"
level = 0
race = "divine_beast"
attribute = "divine"
# strings = []
category = "banish negate_effect damage_lp special_summon"

[[card]]
id = 1090076082
name = "${SU| Cujoh Jolyne}"
set = "standuser"
type = "monster effect"
effect = """If a monster attacks this face-up card: You can negate the attack. You can only use this effect of "${SU| Cujoh Jolyne}" once ${PT}."""
atk = 1200
def = 1500
level = 4
race = "warrior"
attribute = "earth"
strings = ["Negate attack"]

[[card]]
id = 1090076083
name = "${SP| Stone Free}"
set = "standpower"
type = "spell equip"
effect = """${StandText|Stone Free|Cujoh Jolyne}
While this card is equipped to a monster:
• It gains 800 ATK;
• It can attack twice per ${BP};
• The equipped monster can attack your opponent directly, but when it does so using this effect, at the start of the ${DS}: It loses 700 ATK until the next ${SbP}."""
# strings = []
category = "destroy_monster destroy_st change_atk_def multi_attack"
