[macro]
PT = "per turn"
OPT = "Once ${PT}"
SbP = "Standby Phase"
QE = "(Quick Effect)"
BP = "Battle Phase"
DS = "Damage Step"
SU = "Stand User$1"
SP = "Stand Power$1"
StandText = """You can only control 1 "${SP| $1}". Can only be equipped to a "${SU| $2}" you control. If the monster this card is equipped to would be destroyed by battle or card effect: You can destroy this card instead."""

[set.standuser]
name = "${SU}"
code = 0xf00

[set.standpower]
name = "${SP}"
code = 0xf01

[set.niimiyo]
name = "Nii Miyo - JJBA"
code = 0xf02
# To easy search the cards
